# bindsym $mod+w exec $browser ; mode "default"
bindsym $mod+i exec $incognito ; mode "default"
bindsym $mod+n exec $filemanager ; mode "default"
# bindsym $mod+o exec $pdfreader ; mode "default"
# bindsym $mod+b exec $blueman ; mode "default"
bindsym $mod+p exec $audio_settings ; mode "default"
bindsym $mod+m exec $musicplayer ; mode "default"
bindsym $mod+u exec $backgrounds ; mode "default"

# APPLICATIONS TO APPEAR IN SPECIFIC WORKSPACES
for_window [app_id=.*] focus
assign [app_id="thunar"] 3
assign [app_id="foot"] 1
assign [app_id="firefox"] 2
assign [app_id="thunar"] 3
assign [app_id="org.keepassxc.KeePassXC"] 3
assign [app_id="cc.cubocore.CorePad"] 4
assign [app_id="libreoffice-writer"] 5
assign [app_id="libreoffice-calc"] 6
assign [app_id="org.kde.okular"] 7
