input "type:touchpad" {
    dwt enabled
    dwtp enabled
    tap enabled
    tap_button_map lrm
    natural_scroll enabled
}

# swipe gestrue
bindgesture swipe:3:right focus next
bindgesture swipe:3:left focus prev

bindgesture swipe:3:up floating enable; [floating con_id="__focused__"] resize set 70ppt 75ppt
bindgesture swipe:3:down floating disable
# bindsym $mod+Shift+y [floating con_id="__focused__"] move position center

bindgesture swipe:4:right workspace next_on_output
bindgesture swipe:4:left workspace prev_on_output

# bindgesture pinch:inward+up move up
# bindgesture pinch:inward+down move down
# bindgesture pinch:inward+left move left
# bindgesture pinch:inward+right move right
