# varialbles
set $mod Mod4

# workspaces
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"

# colors
set $bg #222222
set $fg #d8a657
set $ur #ea6962
set $uf #a89984

# system apps
set $terminal footclient
set $browser firefox --new-tab
set $incognito $browser --new-tab --private-window
set $filemanager thunar
set $pdfreader zathura
set $blueman blueman-manager
set $audio_settings pavucontrol
set $lockscreen swaylock -i ~/.config/walls/wall.png
set $backgrounds ristretto $HOME/Pictures/backgrounds/

# app launcher : rofi
set $rofi_drun rofi -show drun -disable-history -show-icons
set $rofi_run rofi -show run -disable-history
set $rofi_windows rofi -show window -show-icons
set $rofi_emoji rofi -modi emoji -show emoji
